fastlane_version "1.100.0"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore", readonly: true) # more information: https://codesigning.guide
    
    increment_build_number(
      xcodeproj: './ios/Todos.xcodeproj'
    )

    ipa = gym(
      scheme: "Todos",
      project: "./ios/Todos.xcodeproj"
    )

    pilot(ipa: ipa)

    clean_build_artifacts

    commit_version_bump(
      message: "👷 Deployed new version #{lane_context[SharedValues::VERSION_NUMBER]}.#{lane_context[SharedValues::BUILD_NUMBER]} [skip ci]",
      xcodeproj: './ios/Todos.xcodeproj'
    )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end
