export const LOAD_TASKS_REQUEST = 'LOAD_TASKS_REQUEST';
export const LOAD_TASKS_ERROR = 'LOAD_TASKS_ERROR';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';

export const TOGGLE_TASK_COMPLETION_REQUEST = 'TOGGLE_TASK_COMPLETION_REQUEST';
export const TOGGLE_TASK_COMPLETION_ERROR = 'TOGGLE_TASK_COMPLETION_ERROR';
export const TOGGLE_TASK_COMPLETION_SUCCESS = 'TOGGLE_TASK_COMPLETION_SUCCESS';

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
